#!/usr/bin/env bash
set -euo pipefail

base_ref="${1:-origin/main}"
allowed='^(README\.md$|src/|tests/Architecture/|tests/Live/(i9-public-readonly\.spec\.cjs|playwright\.i9-public\.config\.cjs)$|tools/(i9-evidence-(validator|init|record|integrity|readiness)|lego-(staging-verify|acceptance-(validate|init|record|report)|release-acceptance-init))\.cjs$|assets/(site-builder-runtime|interaction-runtime|ultimate-designer-admin|ultimate-designer-menu-admin|ultimate-designer-menu-pages|ultimate-designer-side-health|ultimate-designer-asset-admin|ultimate-designer-portability|ultimate-designer-permissions|ultimate-designer-ai|ultimate-designer-qa|ultimate-designer-conversion|ultimate-designer-layout-tools|ultimate-designer-box-tools|ultimate-designer-nesting-tools|ultimate-designer-box-content-layout|ultimate-designer-visual-composition|ultimate-designer-table-appearance|ultimate-designer-element-library|ultimate-designer-workspace-widgets|ultimate-designer-unsaved-preview|ultimate-designer-lego-spacing-v0830|ultimate-designer-lego-spacing-v0831|ultimate-designer-lego-design-v0832|ultimate-designer-lego-design-event-guard-v0832|ultimate-designer-lego-design-responsive-v0833|ultimate-designer-lego-design-responsive-event-guard-v0833|ultimate-designer-lego-interaction-states-v0834|ultimate-designer-lego-interaction-states-event-guard-v0834|ultimate-designer-lego-interaction-snapshot-v0834|ultimate-designer-lego-primary-view-v0836|ultimate-designer-lego-layout-primary-v0837|ultimate-designer-lego-drop-zones-v0838|ultimate-designer-lego-palette-side-drop-bridge-v0843|ultimate-designer-lego-parent-key-guard-v0845|ultimate-designer-page-delete-v0844|ultimate-designer-canvas-panel-collapse-v0839|ultimate-designer-history-v0817|ultimate-designer-history-v0818|ultimate-designer-history-preload-v0820|ultimate-designer-history-preload-v0821|ultimate-designer-history-post-restore-v0822|ultimate-designer-history-content-v0823|ultimate-designer-history-atomic-v0840|ultimate-designer-lego-resize-v0841|ultimate-designer-lego-responsive-layout-v0842)\.(js|css)$|docs/(architecture-|ud-|v085-|v0816-|v0817-|v0818-|v0830-|v0831-|v0832-|v0833-|v0834-|v0835-|v0836-|v0837-|v0838-|v0840-|v0841-|v0842-|b2-|i9-|i10-|lego-)[^/]+\.md$|docs/(i9-evidence-manifest|lego-manual-acceptance)\.(schema|example)\.json$|docs/lego-v084(0|1|2|3)-manual-acceptance\.json$|docs/active-backlog-v084(0|1|2)\.md$|docs/ultimate-designer-(onboarding|user-manual|quick-reference)\.md$|docs/migration-operations-index\.md$|docs/integration-backlog-after-ud120\.md$|\.github/workflows/(architecture-foundation-qa|editor-runtime-fast-qa|event-auto-archive-qa|b1-backup-restore-qa|b2-site-backup-qa|lego-spacing-qa|lego-staging-build|i9-test2-live-readonly|i9-prep-qa|i9-evidence-validate)\.yml$)'
changed="$(git diff --name-only "${base_ref}...HEAD")"
violations="$(printf '%s\n' "$changed" | grep -Ev "$allowed" || true)"
if [[ -n "$violations" ]]; then
  echo "Architecture isolation FAILED."
  echo "Existing legacy/public runtime files were changed during a non-invasive architecture phase:"
  printf '%s\n' "$violations"
  exit 1
fi
echo "Architecture isolation: PASS"
echo "Existing legacy/public runtime files remain untouched; extracted services, tests/docs and dedicated Ultimate Designer admin assets are allowed."
