from pathlib import Path

P=Path('hangar18-manager.php'); J=Path('assets/admin.js'); C=Path('assets/admin.css'); R=Path('readme.txt')

def once(s,a,b,label):
    n=s.count(a)
    if n!=1: raise SystemExit(f'{label}: expected 1 match, got {n}')
    return s.replace(a,b,1)

s=P.read_text(encoding='utf-8')
s=once(s,'* Version: 0.5.5','* Version: 0.5.6','header version')
s=once(s,"const VERSION = '0.5.5';","const VERSION = '0.5.6';",'const version')
if s.count("'1.9'")!=7: raise SystemExit(f"schema 1.9 count={s.count(chr(39)+'1.9'+chr(39))}")
s=s.replace("'1.9'","'1.10'")

old="""            'HoverEffect'            => 'None',\n            'HoverTransitionMs'      => 220,\n            'ShowDesktop'            => true,"""
new="""            'HoverEffect'            => 'None',\n            'HoverTransitionMs'      => 220,\n            'HoverStyleMode'         => 'Inherit',\n            'HoverBackgroundColor'   => '#ffffff',\n            'HoverTextColor'         => '#30382a',\n            'HoverHeadingColor'      => '#30382a',\n            'HoverBorderColor'       => '#c3ae83',\n            'HoverOpacityPercent'    => 100,\n            'ShowDesktop'            => true,"""
s=once(s,old,new,'hover state defaults')

old="""        $hover_effect = (string) ($raw['HoverEffect'] ?? 'None');\n        if (!in_array($hover_effect, ['None', 'Lift', 'Scale', 'Shadow'], true)) { $hover_effect = 'None'; }\n        $tablet_alignment = (string) ($raw['TabletAlignment'] ?? 'Inherit');"""
new="""        $hover_effect = (string) ($raw['HoverEffect'] ?? 'None');\n        if (!in_array($hover_effect, ['None', 'Lift', 'Scale', 'Shadow'], true)) { $hover_effect = 'None'; }\n        $hover_style_mode = (string) ($raw['HoverStyleMode'] ?? 'Inherit');\n        if (!in_array($hover_style_mode, ['Inherit', 'Custom'], true)) { $hover_style_mode = 'Inherit'; }\n        $hover_background = sanitize_hex_color((string) ($raw['HoverBackgroundColor'] ?? '#ffffff')) ?: '#ffffff';\n        $hover_text = sanitize_hex_color((string) ($raw['HoverTextColor'] ?? '#30382a')) ?: '#30382a';\n        $hover_heading = sanitize_hex_color((string) ($raw['HoverHeadingColor'] ?? '#30382a')) ?: '#30382a';\n        $hover_border = sanitize_hex_color((string) ($raw['HoverBorderColor'] ?? '#c3ae83')) ?: '#c3ae83';\n        $tablet_alignment = (string) ($raw['TabletAlignment'] ?? 'Inherit');"""
s=once(s,old,new,'hover normalization')

old="""            'HoverEffect'            => $hover_effect,\n            'HoverTransitionMs'      => $this->clamp_int($raw['HoverTransitionMs'] ?? 220, 0, 1000, 220),\n            'ShowDesktop'            => array_key_exists('ShowDesktop', $raw) ? !empty($raw['ShowDesktop']) : true,"""
new="""            'HoverEffect'            => $hover_effect,\n            'HoverTransitionMs'      => $this->clamp_int($raw['HoverTransitionMs'] ?? 220, 0, 1000, 220),\n            'HoverStyleMode'         => $hover_style_mode,\n            'HoverBackgroundColor'   => $hover_background,\n            'HoverTextColor'         => $hover_text,\n            'HoverHeadingColor'      => $hover_heading,\n            'HoverBorderColor'       => $hover_border,\n            'HoverOpacityPercent'    => $this->clamp_int($raw['HoverOpacityPercent'] ?? 100, 0, 100, 100),\n            'ShowDesktop'            => array_key_exists('ShowDesktop', $raw) ? !empty($raw['ShowDesktop']) : true,"""
s=once(s,old,new,'hover normalized fields')

old="""        $hover_effect = (string) ($section['HoverEffect'] ?? 'None');\n        $hover_y = '0px';"""
new="""        $hover_effect = (string) ($section['HoverEffect'] ?? 'None');\n        $hover_style_custom = ($section['HoverStyleMode'] ?? 'Inherit') === 'Custom';\n        $hover_background = $hover_style_custom ? (string) ($section['HoverBackgroundColor'] ?? '#ffffff') : $bg;\n        $hover_text = $hover_style_custom ? (string) ($section['HoverTextColor'] ?? '#30382a') : $text;\n        $hover_heading = $hover_style_custom ? (string) ($section['HoverHeadingColor'] ?? '#30382a') : $heading;\n        $hover_border = $hover_style_custom ? (string) ($section['HoverBorderColor'] ?? '#c3ae83') : (string) ($section['CustomBorderColor'] ?? '#c3ae83');\n        $hover_opacity = $hover_style_custom ? (max(0, min(100, (int) ($section['HoverOpacityPercent'] ?? 100))) / 100) : $opacity;\n        $hover_background_image = $hover_style_custom ? 'none' : $effect_image;\n        $hover_y = '0px';"""
s=once(s,old,new,'hover state runtime calculations')

old="""            '--h18-hover-active-scale:' . $hover_scale . ';' .\n            '--h18-hover-shadow:' . $hover_shadow . ';' .\n            '--h18-hover-transition:' . (int) ($section['HoverTransitionMs'] ?? 220) . 'ms;';"""
new="""            '--h18-hover-active-scale:' . $hover_scale . ';' .\n            '--h18-hover-shadow:' . $hover_shadow . ';' .\n            '--h18-hover-bg:' . $hover_background . ';' .\n            '--h18-hover-bg-image:' . $hover_background_image . ';' .\n            '--h18-hover-text:' . $hover_text . ';' .\n            '--h18-hover-heading:' . $hover_heading . ';' .\n            '--h18-hover-border:' . $hover_border . ';' .\n            '--h18-hover-opacity:' . $hover_opacity . ';' .\n            '--h18-hover-transition:' . (int) ($section['HoverTransitionMs'] ?? 220) . 'ms;';"""
s=once(s,old,new,'hover state CSS vars')

old="""            'body.page .h18-editor-page>.h18-editor-section{background-color:var(--h18-section-bg)!important;background-image:var(--h18-section-bg-image,none);background-position:var(--h18-section-bg-position,center);background-size:var(--h18-section-bg-size,cover);background-repeat:no-repeat;color:var(--h18-section-text)!important;border:var(--h18-section-border-width,0) solid var(--h18-section-border,transparent);border-radius:var(--h18-radius-tl,var(--h18-radius,0)) var(--h18-radius-tr,var(--h18-radius,0)) var(--h18-radius-br,var(--h18-radius,0)) var(--h18-radius-bl,var(--h18-radius,0));box-shadow:var(--h18-section-shadow,none);opacity:var(--h18-section-opacity,1);font-family:var(--h18-section-body-font);font-size:var(--h18-section-body-size);transform:translate(var(--h18-transform-x,0px),var(--h18-transform-y,0px)) translateY(var(--h18-hover-y,0px)) scale(var(--h18-transform-scale,1)) scale(var(--h18-hover-scale,1)) rotate(var(--h18-transform-rotate,0deg));transition:transform var(--h18-hover-transition,220ms) ease,box-shadow var(--h18-hover-transition,220ms) ease,opacity var(--h18-hover-transition,220ms) ease}' .\n            '@media(hover:hover){body.page .h18-editor-page>.h18-editor-section:hover{--h18-hover-y:var(--h18-hover-active-y,0px);--h18-hover-scale:var(--h18-hover-active-scale,1);box-shadow:var(--h18-hover-shadow,var(--h18-section-shadow,none))}}' ."""
new="""            'body.page .h18-editor-page>.h18-editor-section{background-color:var(--h18-section-bg)!important;background-image:var(--h18-section-bg-image,none);background-position:var(--h18-section-bg-position,center);background-size:var(--h18-section-bg-size,cover);background-repeat:no-repeat;color:var(--h18-section-text)!important;border:var(--h18-section-border-width,0) solid var(--h18-section-border,transparent);border-radius:var(--h18-radius-tl,var(--h18-radius,0)) var(--h18-radius-tr,var(--h18-radius,0)) var(--h18-radius-br,var(--h18-radius,0)) var(--h18-radius-bl,var(--h18-radius,0));box-shadow:var(--h18-section-shadow,none);opacity:var(--h18-section-opacity,1);font-family:var(--h18-section-body-font);font-size:var(--h18-section-body-size);transform:translate(var(--h18-transform-x,0px),var(--h18-transform-y,0px)) translateY(var(--h18-hover-y,0px)) scale(var(--h18-transform-scale,1)) scale(var(--h18-hover-scale,1)) rotate(var(--h18-transform-rotate,0deg));transition:transform var(--h18-hover-transition,220ms) ease,box-shadow var(--h18-hover-transition,220ms) ease,opacity var(--h18-hover-transition,220ms) ease,background-color var(--h18-hover-transition,220ms) ease,color var(--h18-hover-transition,220ms) ease,border-color var(--h18-hover-transition,220ms) ease}' .\n            '@media(hover:hover){body.page .h18-editor-page>.h18-editor-section:hover{--h18-hover-y:var(--h18-hover-active-y,0px);--h18-hover-scale:var(--h18-hover-active-scale,1);background-color:var(--h18-hover-bg,var(--h18-section-bg))!important;background-image:var(--h18-hover-bg-image,var(--h18-section-bg-image,none));color:var(--h18-hover-text,var(--h18-section-text))!important;border-color:var(--h18-hover-border,var(--h18-section-border,transparent));opacity:var(--h18-hover-opacity,var(--h18-section-opacity,1));box-shadow:var(--h18-hover-shadow,var(--h18-section-shadow,none))}body.page .h18-editor-page>.h18-editor-section:hover h1,body.page .h18-editor-page>.h18-editor-section:hover h2,body.page .h18-editor-page>.h18-editor-section:hover h3{color:var(--h18-hover-heading,var(--h18-section-heading))!important}body.page .h18-editor-page>.h18-editor-section:hover .h18-editor-grid-card h3{color:inherit!important}}' ."""
s=once(s,old,new,'hover state frontend CSS')

# Insert hover state UI immediately after hover movement controls and before gradient fields.
old="""                                    <div class=\"h18-field\"><label><strong>Hover-transition (ms)</strong></label><input type=\"number\" min=\"0\" max=\"1000\" step=\"10\" name=\"<?php echo esc_attr($prefix); ?>[HoverTransitionMs]\" value=\"<?php echo esc_attr($section['HoverTransitionMs']); ?>\" /></div>\n                                </div>\n                                <div class=\"h18-bg-gradient-fields h18-module-fields-grid h18-module-fields-grid--four\">"""
new="""                                    <div class=\"h18-field\"><label><strong>Hover-transition (ms)</strong></label><input type=\"number\" min=\"0\" max=\"1000\" step=\"10\" name=\"<?php echo esc_attr($prefix); ?>[HoverTransitionMs]\" value=\"<?php echo esc_attr($section['HoverTransitionMs']); ?>\" /></div>\n                                </div>\n                                <div class=\"h18-hover-state-box\">\n                                    <h4>Hover-state</h4>\n                                    <div class=\"h18-field\"><label><strong>Hover-farver</strong></label><select class=\"h18-hover-style-mode\" name=\"<?php echo esc_attr($prefix); ?>[HoverStyleMode]\"><option value=\"Inherit\" <?php selected($section['HoverStyleMode'], 'Inherit'); ?>>Arv Normal</option><option value=\"Custom\" <?php selected($section['HoverStyleMode'], 'Custom'); ?>>Tilpasset solid state</option></select></div>\n                                    <div class=\"h18-hover-style-fields h18-module-fields-grid h18-module-fields-grid--four\">\n                                        <div class=\"h18-field\"><label><strong>Baggrund</strong></label><input type=\"color\" name=\"<?php echo esc_attr($prefix); ?>[HoverBackgroundColor]\" value=\"<?php echo esc_attr($section['HoverBackgroundColor']); ?>\" /></div>\n                                        <div class=\"h18-field\"><label><strong>Tekst</strong></label><input type=\"color\" name=\"<?php echo esc_attr($prefix); ?>[HoverTextColor]\" value=\"<?php echo esc_attr($section['HoverTextColor']); ?>\" /></div>\n                                        <div class=\"h18-field\"><label><strong>Overskrift</strong></label><input type=\"color\" name=\"<?php echo esc_attr($prefix); ?>[HoverHeadingColor]\" value=\"<?php echo esc_attr($section['HoverHeadingColor']); ?>\" /></div>\n                                        <div class=\"h18-field\"><label><strong>Kant</strong></label><input type=\"color\" name=\"<?php echo esc_attr($prefix); ?>[HoverBorderColor]\" value=\"<?php echo esc_attr($section['HoverBorderColor']); ?>\" /></div>\n                                        <div class=\"h18-field\"><label><strong>Opacity (%)</strong></label><input type=\"number\" min=\"0\" max=\"100\" name=\"<?php echo esc_attr($prefix); ?>[HoverOpacityPercent]\" value=\"<?php echo esc_attr($section['HoverOpacityPercent']); ?>\" /></div>\n                                    </div>\n                                </div>\n                                <div class=\"h18-bg-gradient-fields h18-module-fields-grid h18-module-fields-grid--four\">"""
s=once(s,old,new,'hover state admin UI')
P.write_text(s,encoding='utf-8')

j=J.read_text(encoding='utf-8')
old="""    function refreshSectionBackgroundEffect($row) {\n        if (!$row || !$row.length) { return; }\n        const effect = String(pageSectionControls($row, '.h18-section-background-effect').val() || 'None');\n        pageSectionControls($row, '.h18-bg-gradient-fields').toggle(effect === 'Gradient');\n        pageSectionControls($row, '.h18-bg-image-fields').toggle(effect === 'Image');\n    }\n\n    function refreshPageSectionType($row) {"""
new="""    function refreshSectionBackgroundEffect($row) {\n        if (!$row || !$row.length) { return; }\n        const effect = String(pageSectionControls($row, '.h18-section-background-effect').val() || 'None');\n        pageSectionControls($row, '.h18-bg-gradient-fields').toggle(effect === 'Gradient');\n        pageSectionControls($row, '.h18-bg-image-fields').toggle(effect === 'Image');\n    }\n\n    function refreshHoverStyleMode($row) {\n        if (!$row || !$row.length) { return; }\n        const custom = String(pageSectionControls($row, '.h18-hover-style-mode').val() || 'Inherit') === 'Custom';\n        pageSectionControls($row, '.h18-hover-style-fields').toggle(custom);\n    }\n\n    function refreshPageSectionType($row) {"""
j=once(j,old,new,'hover js refresh function')
old="""        refreshSectionDesignMode($row);\n        refreshSectionBackgroundEffect($row);\n        rebuildPageNavigator();"""
new="""        refreshSectionDesignMode($row);\n        refreshSectionBackgroundEffect($row);\n        refreshHoverStyleMode($row);\n        rebuildPageNavigator();"""
j=once(j,old,new,'hover refresh call')
old="""    $(document).on('change', '.h18-section-background-effect', function () { refreshSectionBackgroundEffect(pageSectionForElement(this)); });"""
new=old+"\n    $(document).on('change', '.h18-hover-style-mode', function () { refreshHoverStyleMode(pageSectionForElement(this)); });"
j=once(j,old,new,'hover change handler')
J.write_text(j,encoding='utf-8')

c=C.read_text(encoding='utf-8')
c += """\n\n/* v0.5.6 hover state styling */\n.h18-hover-state-box{margin-top:12px;padding:12px;border:1px solid #dcdcde;border-radius:7px;background:#fff}\n.h18-hover-state-box>h4:first-child{margin-top:0}\n.h18-hover-style-fields{margin-top:10px}\n"""
C.write_text(c,encoding='utf-8')

r=R.read_text(encoding='utf-8')
r=once(r,'Version: 0.5.5','Version: 0.5.6','readme version')
marker='Webbaseret management-værktøj til Aalborg Kaserners Veteran Panser- og Køretøjsforening.\n'
notes="""\n== Version 0.5.6 – Normal/Hover states ==\n\nNyt:\n- hover-state kan arve Normal eller have egne farver\n- egen hover-baggrund, tekst, overskrift, kant og opacity\n- tilpasset hover-baggrund er en solid state og erstatter gradient/billede under hover\n- hover state kombineres med v0.5.4-bevægelse/skygge og v0.5.5-device transforms\n- page-editor schema 1.10; standarden Arv Normal bevarer eksisterende design\n\n"""
r=once(r,marker,marker+notes,'readme notes')
R.write_text(r,encoding='utf-8')
print('v0.5.6 hover state patch applied')
