from pathlib import Path
p=Path('hangar18-manager.php'); t=p.read_text(encoding='utf-8')
anchor='''                            </div>\n                        </div>\n                    </details>\n                <?php endif; ?>'''
box='''                            </div>\n                            <div class="h18-element-typography-box">\n                                <h4>Typografi for dette element</h4>\n                                <p class="description">Global font og værdien 0 arver det centrale designsystem.</p>\n                                <div class="h18-module-fields-grid h18-module-fields-grid--four">\n                                    <div class="h18-field"><label><strong>Brødtekst-font</strong></label><select name="<?php echo esc_attr($prefix); ?>[SectionBodyFontFamily]"><?php foreach (['Global','System','Segoe UI','Arial','Verdana','Tahoma','Trebuchet MS','Georgia','Times New Roman','Courier New'] as $font) : ?><option value="<?php echo esc_attr($font); ?>" <?php selected($section['SectionBodyFontFamily'], $font); ?>><?php echo esc_html($font === 'Global' ? 'Global font' : $font); ?></option><?php endforeach; ?></select></div>\n                                    <div class="h18-field"><label><strong>Overskrift-font</strong></label><select name="<?php echo esc_attr($prefix); ?>[SectionHeadingFontFamily]"><?php foreach (['Global','System','Segoe UI','Arial','Verdana','Tahoma','Trebuchet MS','Georgia','Times New Roman','Courier New'] as $font) : ?><option value="<?php echo esc_attr($font); ?>" <?php selected($section['SectionHeadingFontFamily'], $font); ?>><?php echo esc_html($font === 'Global' ? 'Global font' : $font); ?></option><?php endforeach; ?></select></div>\n                                    <div class="h18-field"><label><strong>Brødtekst (px)</strong></label><input type="number" min="0" max="32" name="<?php echo esc_attr($prefix); ?>[BodyFontSizePx]" value="<?php echo esc_attr($section['BodyFontSizePx']); ?>" /><p class="description">0 = global størrelse</p></div>\n                                    <div class="h18-field"><label><strong>H1 (px)</strong></label><input type="number" min="0" max="96" name="<?php echo esc_attr($prefix); ?>[H1FontSizePx]" value="<?php echo esc_attr($section['H1FontSizePx']); ?>" /><p class="description">0 = global størrelse</p></div>\n                                    <div class="h18-field"><label><strong>H2 (px)</strong></label><input type="number" min="0" max="80" name="<?php echo esc_attr($prefix); ?>[H2FontSizePx]" value="<?php echo esc_attr($section['H2FontSizePx']); ?>" /><p class="description">0 = global størrelse</p></div>\n                                    <div class="h18-field"><label><strong>H3 (px)</strong></label><input type="number" min="0" max="64" name="<?php echo esc_attr($prefix); ?>[H3FontSizePx]" value="<?php echo esc_attr($section['H3FontSizePx']); ?>" /><p class="description">0 = global størrelse</p></div>\n                                </div>\n                            </div>\n                        </div>\n                    </details>\n                <?php endif; ?>'''
if anchor not in t: raise SystemExit('typography UI anchor missing')
p.write_text(t.replace(anchor,box,1),encoding='utf-8')

c=Path('assets/admin.css'); css=c.read_text(encoding='utf-8')
css+='''\n\n/* v0.5.3 – typografi pr. element */\n.h18-element-typography-box{margin-top:16px;padding-top:16px;border-top:1px solid #dcdcde}\n.h18-element-typography-box h4{margin:0 0 5px}\n.h18-element-typography-box>.description{margin:0 0 12px}\n'''
c.write_text(css,encoding='utf-8')

r=Path('readme.txt'); readme=r.read_text(encoding='utf-8')
if 'Version: 0.5.2' not in readme: raise SystemExit('readme version missing')
readme=readme.replace('Version: 0.5.2','Version: 0.5.3',1)
readme+='''\n\n== Version 0.5.3 – Typografi pr. element ==\n\n- Hver editorsektion kan vælge egen brødtekstfont og overskriftsfont eller arve de globale fonte.\n- Brødtekst samt H1, H2 og H3 kan få egne størrelser pr. element.\n- Værdien 0 betyder global størrelse og giver fuld bagudkompatibilitet.\n- Typografifelterne gemmes også i genbrugelige komponenter fra v0.5.1.\n- Page-editor dataformatet er kompatibelt løftet fra schema 1.6 til 1.7.\n'''
r.write_text(readme,encoding='utf-8')
